version: '3.6'
services:
    hellish:
        build: .
        ports:
            - 1337:7480
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_PTRACE
        environment:
            - LANG=en_US.utf8
