services:
  redis:
    container_name: library-redis
    image: "redis:6-alpine"

  web:
    container_name: library-web
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - FLAG=CE441{fake_flag}
    depends_on:
      - redis
    ports:
      - "8080:8080"

  bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.bot
    shm_size: 2gb
    depends_on:
      - redis
